//! The public surface of [`nbtx::Value`], [`nbtx::Compound`] and
//! [`nbtx::FieldType`], exercised directly rather than incidentally.
//!
//! The accessors are generated by a macro, so a mistake in it would be
//! *systematic*: every `as_*`/`is_*`/`into_*` would be wrong the same way, and a
//! round-trip test that only ever calls `as_compound` on a compound would never
//! notice. These tests therefore run the full 12 × 12 matrix — each variant
//! against each accessor — instead of spot-checking.
//!
//! No codec is involved, so this file builds without the `nbt`/`snbt` features.

use bstr::BString;
use nbtx::{Compound, FieldType, Value};

/// One of every variant, in tag order, with a distinguishable payload.
fn all_variants() -> Vec<Value> {
    vec![
        Value::Byte(1),
        Value::Short(2),
        Value::Int(3),
        Value::Long(4),
        Value::Float(5.0),
        Value::Double(6.0),
        Value::ByteArray(vec![7]),
        Value::String(BString::from("8")),
        Value::List(vec![Value::Byte(9)]),
        Value::Compound(Compound::from([(BString::from("k"), Value::Byte(10))])),
        Value::IntArray(vec![11]),
        Value::LongArray(vec![12]),
    ]
}

/// Applies every `is_*` predicate to `v` and returns the tag ids that answered
/// `true`. A correct implementation always returns exactly one.
fn matching_predicates(v: &Value) -> Vec<u8> {
    let checks: [(u8, bool); 12] = [
        (1, v.is_byte()),
        (2, v.is_short()),
        (3, v.is_int()),
        (4, v.is_long()),
        (5, v.is_float()),
        (6, v.is_double()),
        (7, v.is_byte_array()),
        (8, v.is_string()),
        (9, v.is_list()),
        (10, v.is_compound()),
        (11, v.is_int_array()),
        (12, v.is_long_array()),
    ];
    checks
        .iter()
        .filter(|(_, hit)| *hit)
        .map(|(id, _)| *id)
        .collect()
}

/// Applies every `as_*` accessor and returns the tag ids that answered `Some`.
fn matching_accessors(v: &Value) -> Vec<u8> {
    let checks: [(u8, bool); 12] = [
        (1, v.as_byte().is_some()),
        (2, v.as_short().is_some()),
        (3, v.as_int().is_some()),
        (4, v.as_long().is_some()),
        (5, v.as_float().is_some()),
        (6, v.as_double().is_some()),
        (7, v.as_byte_array().is_some()),
        (8, v.as_string().is_some()),
        (9, v.as_list().is_some()),
        (10, v.as_compound().is_some()),
        (11, v.as_int_array().is_some()),
        (12, v.as_long_array().is_some()),
    ];
    checks
        .iter()
        .filter(|(_, hit)| *hit)
        .map(|(id, _)| *id)
        .collect()
}

/// Exactly one `is_*` predicate answers `true` for each variant, and it is the
/// one matching that variant's tag.
#[test]
fn each_is_predicate_matches_exactly_one_variant() {
    for v in all_variants() {
        assert_eq!(
            matching_predicates(&v),
            vec![v.discriminant()],
            "{v:?}: exactly one is_* predicate must hold, and it must be its own"
        );
    }
}

/// The same claim for the `as_*` accessors: they must be `None` for all eleven
/// other variants, not merely `Some` for their own.
#[test]
fn each_as_accessor_matches_exactly_one_variant() {
    for v in all_variants() {
        assert_eq!(
            matching_accessors(&v),
            vec![v.discriminant()],
            "{v:?}: exactly one as_* accessor must return Some"
        );
    }
}

/// `as_*` returns a reference to the *actual* payload, not a defaulted or
/// converted one.
#[test]
fn as_accessors_return_the_real_payload() {
    assert_eq!(Value::Byte(-1).as_byte(), Some(&-1i8));
    assert_eq!(Value::Short(-2).as_short(), Some(&-2i16));
    assert_eq!(Value::Int(-3).as_int(), Some(&-3i32));
    assert_eq!(Value::Long(-4).as_long(), Some(&-4i64));
    assert_eq!(Value::Float(1.5).as_float(), Some(&1.5f32));
    assert_eq!(Value::Double(2.5).as_double(), Some(&2.5f64));
    assert_eq!(
        Value::String(BString::from("hi")).as_string(),
        Some(&BString::from("hi"))
    );
    assert_eq!(
        Value::ByteArray(vec![1, 2]).as_byte_array(),
        Some(&vec![1u8, 2])
    );
    assert_eq!(
        Value::IntArray(vec![1, 2]).as_int_array(),
        Some(&vec![1i32, 2])
    );
    assert_eq!(
        Value::LongArray(vec![1, 2]).as_long_array(),
        Some(&vec![1i64, 2])
    );
    assert_eq!(
        Value::List(vec![Value::Byte(1)]).as_list().unwrap().len(),
        1
    );
    assert_eq!(
        Value::Compound(Compound::new())
            .as_compound()
            .unwrap()
            .len(),
        0
    );
}

/// `into_*` takes ownership and, crucially, hands the value **back** on a
/// mismatch instead of dropping it — that is what makes it usable in a chain of
/// fallible conversions.
#[test]
fn into_accessors_return_the_value_unchanged_on_a_mismatch() {
    assert_eq!(Value::Int(7).into_int(), Ok(7));
    assert_eq!(Value::Byte(7).into_int(), Err(Value::Byte(7)));

    // The returned value is the original, not a rebuilt one: a payload the
    // accessor could not have reconstructed still comes back intact.
    let original = Value::Compound(Compound::from([(BString::from("k"), Value::Long(9))]));
    let Err(returned) = original.clone().into_list() else {
        panic!("a Compound must not convert into a List");
    };
    assert_eq!(returned, original);
}

/// Every `into_*` succeeds for its own variant and fails for all others,
/// mirroring the `as_*` matrix.
#[test]
fn each_into_accessor_succeeds_only_for_its_own_variant() {
    for v in all_variants() {
        let d = v.discriminant();
        let results: [(u8, bool); 12] = [
            (1, v.clone().into_byte().is_ok()),
            (2, v.clone().into_short().is_ok()),
            (3, v.clone().into_int().is_ok()),
            (4, v.clone().into_long().is_ok()),
            (5, v.clone().into_float().is_ok()),
            (6, v.clone().into_double().is_ok()),
            (7, v.clone().into_byte_array().is_ok()),
            (8, v.clone().into_string().is_ok()),
            (9, v.clone().into_list().is_ok()),
            (10, v.clone().into_compound().is_ok()),
            (11, v.clone().into_int_array().is_ok()),
            (12, v.clone().into_long_array().is_ok()),
        ];
        let hits: Vec<u8> = results
            .iter()
            .filter(|(_, ok)| *ok)
            .map(|(id, _)| *id)
            .collect();
        assert_eq!(hits, vec![d], "{v:?}: exactly one into_* must succeed");
    }
}

/// `discriminant` is the wire tag id, so it must match `FieldType`'s numbering
/// exactly — the codecs write it straight into the stream.
#[test]
fn discriminant_matches_the_field_type_numbering() {
    let expected = [
        FieldType::Byte,
        FieldType::Short,
        FieldType::Int,
        FieldType::Long,
        FieldType::Float,
        FieldType::Double,
        FieldType::ByteArray,
        FieldType::String,
        FieldType::List,
        FieldType::Compound,
        FieldType::IntArray,
        FieldType::LongArray,
    ];
    for (v, ty) in all_variants().iter().zip(expected) {
        assert_eq!(v.discriminant(), ty as u8, "{v:?} vs {ty}");
    }
    // TAG_End has no `Value` variant: it is a container terminator, not a value.
    assert_eq!(FieldType::End as u8, 0);
    assert!(all_variants().iter().all(|v| v.discriminant() != 0));
}

/// `FieldType`'s `Display` is what error messages quote, so it must name every
/// tag and never fall through to a placeholder.
#[test]
fn field_type_displays_a_name_for_every_tag() {
    let names = [
        (FieldType::End, "end"),
        (FieldType::Byte, "byte"),
        (FieldType::Short, "short"),
        (FieldType::Int, "int"),
        (FieldType::Long, "long"),
        (FieldType::Float, "float"),
        (FieldType::Double, "double"),
        (FieldType::ByteArray, "byte array"),
        (FieldType::String, "string"),
        (FieldType::List, "list"),
        (FieldType::Compound, "compound"),
        (FieldType::IntArray, "int array"),
        (FieldType::LongArray, "long array"),
    ];
    for (ty, name) in names {
        assert_eq!(ty.to_string(), name);
    }
}

/// Comparing a `Value` against a plain Rust scalar is the ergonomic shortcut the
/// `PartialEq<T>` impls exist for; it must be tag-aware, so a numerically equal
/// value under the wrong tag is still unequal.
#[test]
fn partial_eq_against_rust_scalars_is_tag_aware() {
    assert!(Value::Byte(1) == 1i8);
    assert!(Value::Short(1) == 1i16);
    assert!(Value::Int(1) == 1i32);
    assert!(Value::Long(1) == 1i64);
    assert!(Value::Float(1.5) == 1.5f32);
    assert!(Value::Double(1.5) == 1.5f64);

    // Right tag, wrong number.
    assert!(Value::Int(1) != 2i32);
    // Right number, wrong tag: an `Int` is not an `i64` no matter its value.
    assert!(Value::Int(1) != 1i64);
    assert!(Value::Long(1) != 1i32);
    assert!(Value::Float(1.0) != 1.0f64);
}

/// The slice and `&str` comparisons cover the four payload-carrying container
/// tags plus `String`, and must likewise refuse a same-shaped payload under a
/// different tag.
#[test]
fn partial_eq_against_slices_and_str_is_tag_aware() {
    let bytes: &[u8] = &[1, 2];
    let ints: &[i32] = &[1, 2];
    let longs: &[i64] = &[1, 2];
    let items: &[Value] = &[Value::Byte(1)];

    assert!(Value::ByteArray(vec![1, 2]) == bytes);
    assert!(Value::IntArray(vec![1, 2]) == ints);
    assert!(Value::LongArray(vec![1, 2]) == longs);
    assert!(Value::List(vec![Value::Byte(1)]) == items);
    assert!(Value::String(BString::from("hi")) == "hi");

    // An `IntArray` is not a `List`, even element for element.
    assert!(Value::IntArray(vec![1, 2]) != items);
    assert!(Value::ByteArray(vec![1, 2]) != ints);
    assert!(Value::String(BString::from("hi")) != "ho");
}

/// A `Value` compares equal to a bare [`Compound`], which is what makes
/// `assert_eq!(decoded, expected_map)` work without wrapping the map.
#[test]
fn partial_eq_against_a_bare_compound() {
    let map = Compound::from([(BString::from("k"), Value::Int(1))]);
    assert!(Value::Compound(map.clone()) == map);
    assert!(Value::Int(1) != map);
}

/// The same comparisons must work through a reference, because that is how they
/// are reached from a map lookup (`&Value`) or an iterator over a list.
#[test]
fn partial_eq_works_through_references() {
    let v = Value::Int(5);
    let r: &Value = &v;
    assert!(r == 5i32);
    assert!(r != 6i32);

    let mut owned = Value::String(BString::from("hi"));
    let m: &mut Value = &mut owned;
    assert!(m == "hi");

    let list = Value::List(vec![Value::Byte(1), Value::Byte(2)]);
    assert!(list.as_list().unwrap().iter().all(|item| item.is_byte()));
}

/// Comparing two `Value`s never coerces across tags, in either direction. This
/// is the property the tag-preservation guarantees rest on.
#[test]
fn value_equality_never_crosses_tags() {
    let ints = Value::IntArray(vec![1]);
    let list = Value::List(vec![Value::Int(1)]);
    assert_ne!(ints, list);
    assert_ne!(list, ints);
    assert_ne!(Value::Byte(0), Value::Short(0));
    assert_ne!(Value::Float(1.0), Value::Double(1.0));
    assert_ne!(
        Value::ByteArray(vec![b'h', b'i']),
        Value::String(BString::from("hi"))
    );
}

/// `Value`'s equality is **total**: every `NaN` equals every other `NaN`, which
/// is what lets `Value` be `Eq` (and so a `HashMap` key) despite holding
/// `f32`/`f64`. Ordinary IEEE comparison is otherwise untouched, so `-0.0 ==
/// 0.0` still holds.
///
/// Note this says nothing about *bits*: two NaNs with different payloads compare
/// equal, so a test that cares about the payload (`numeric_boundaries`,
/// `cross_variant`) must still compare `to_bits()` rather than the values.
#[test]
fn nan_equals_itself_so_value_can_be_eq() {
    assert_eq!(Value::Double(f64::NAN), Value::Double(f64::NAN));
    assert_eq!(Value::Float(f32::NAN), Value::Float(f32::NAN));

    // Any two NaNs, whatever payload they carry.
    let quiet = Value::Double(f64::NAN);
    let odd = Value::Double(f64::from_bits(0x7ff8_0000_0001_2345));
    assert_eq!(quiet, odd);
    assert_ne!(
        quiet.as_double().unwrap().to_bits(),
        odd.as_double().unwrap().to_bits(),
        "equal, but not the same bits"
    );

    // The same rule on the mixed comparisons, so `v == other_value` and
    // `v == raw_float` cannot disagree.
    assert_eq!(Value::Double(f64::NAN), f64::NAN);
    assert_eq!(Value::Float(f32::NAN), f32::NAN);
    assert_eq!(&Value::Float(f32::NAN), f32::NAN);
    // A NaN is still equal to nothing else.
    assert_ne!(Value::Double(f64::NAN), Value::Double(1.0));
    assert_ne!(Value::Double(f64::NAN), 1.0f64);
    // A NaN inside a container is equal too, which is what makes a whole
    // document with one in it usable as a key.
    assert_eq!(
        Value::List(vec![Value::Float(f32::NAN)]),
        Value::List(vec![Value::Float(f32::NAN)])
    );
}

/// `Hash` must agree with `PartialEq`: `-0.0 == 0.0`, so the two must hash
/// alike, or a `Value` used as a `HashMap` key would go missing.
#[test]
fn hash_agrees_with_equality_for_signed_zero() {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    fn digest(v: &Value) -> u64 {
        let mut h = DefaultHasher::new();
        v.hash(&mut h);
        h.finish()
    }

    assert_eq!(Value::Float(0.0), Value::Float(-0.0));
    assert_eq!(digest(&Value::Float(0.0)), digest(&Value::Float(-0.0)));
    assert_eq!(Value::Double(0.0), Value::Double(-0.0));
    assert_eq!(digest(&Value::Double(0.0)), digest(&Value::Double(-0.0)));

    // Equal values hash equally for the container variants too.
    let a = Value::Compound(Compound::from([(BString::from("k"), Value::Int(1))]));
    let b = Value::Compound(Compound::from([(BString::from("k"), Value::Int(1))]));
    assert_eq!(a, b);
    assert_eq!(digest(&a), digest(&b));

    // ...and for the other case where equal floats have unequal bits: any two
    // NaNs are equal, so any two NaNs must hash alike.
    let quiet = Value::Double(f64::NAN);
    let odd = Value::Double(f64::from_bits(0x7ff8_0000_0001_2345));
    assert_eq!(quiet, odd);
    assert_eq!(digest(&quiet), digest(&odd));
}

/// `Value` is `Eq + Hash`, so it can key a `HashMap` or live in a `HashSet` —
/// the reason to give the floats a total equality rather than dropping `Hash`.
/// Looking a key up by an equal-but-not-identical value must find it, which is
/// exactly the `Eq`/`Hash` contract.
#[test]
fn value_can_key_a_hash_map_and_a_hash_set() {
    use std::collections::{HashMap, HashSet};

    let mut counts: HashMap<Value, u32> = HashMap::new();
    for v in [
        Value::Int(1),
        Value::Int(1),
        Value::Long(1),
        Value::String(BString::from("a")),
        Value::List(vec![Value::Byte(1)]),
        Value::Compound(Compound::from([(BString::from("k"), Value::Int(1))])),
    ] {
        *counts.entry(v).or_default() += 1;
    }
    assert_eq!(counts[&Value::Int(1)], 2);
    // The same number under a different tag is a different key.
    assert_eq!(counts[&Value::Long(1)], 1);
    assert_eq!(counts.len(), 5);

    // A freshly built, structurally equal key finds the stored entry.
    let rebuilt = Value::Compound(Compound::from([(BString::from("k"), Value::Int(1))]));
    assert_eq!(counts[&rebuilt], 1);

    let mut set: HashSet<Value> = HashSet::new();
    assert!(set.insert(Value::Double(f64::NAN)));
    // A NaN key is found again, which a bare IEEE `Eq` could never do.
    assert!(!set.insert(Value::Double(f64::NAN)));
    assert!(set.contains(&Value::Double(f64::from_bits(0x7ff8_0000_0001_2345))));
    // `-0.0` and `0.0` are one key, matching `PartialEq`.
    assert!(set.insert(Value::Float(0.0)));
    assert!(!set.insert(Value::Float(-0.0)));
    assert_eq!(set.len(), 2);
}

/// What `Hash` is *also* good for: digesting a whole document. Two documents
/// that compare equal digest alike, and differing ones — including two tags
/// carrying the same number — do not.
#[test]
fn hash_digests_whole_documents_and_separates_the_tags() {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    fn digest(v: &Value) -> u64 {
        let mut h = DefaultHasher::new();
        v.hash(&mut h);
        h.finish()
    }

    let doc = Value::Compound(Compound::from([
        (BString::from("a"), Value::Int(1)),
        (BString::from("b"), Value::List(vec![Value::Byte(2)])),
    ]));
    assert_eq!(digest(&doc), digest(&doc.clone()));

    // The same number under a different tag must not collide.
    assert_ne!(digest(&Value::Int(1)), digest(&Value::Long(1)));
    assert_ne!(digest(&Value::Byte(1)), digest(&Value::Short(1)));
    // Nor must a changed payload.
    assert_ne!(
        digest(&Value::IntArray(vec![1, 2])),
        digest(&Value::IntArray(vec![2, 1]))
    );
}

/// The `From` conversions are the ergonomic path from Rust text to a `String`
/// tag, and all three must land on the same variant.
#[test]
fn from_conversions_all_produce_a_string_tag() {
    assert_eq!(Value::from("hi"), Value::String(BString::from("hi")));
    assert_eq!(
        Value::from(String::from("hi")),
        Value::String(BString::from("hi"))
    );
    assert_eq!(
        Value::from(BString::from("hi")),
        Value::String(BString::from("hi"))
    );
    // Raw, non-UTF-8 bytes go through `BString`, which is why the conversion is
    // defined on it rather than only on `String`.
    let raw = BString::from(vec![0xffu8, 0xfe]);
    assert!(Value::from(raw.clone()).is_string());
    assert_eq!(Value::from(raw.clone()).as_string(), Some(&raw));
}

/// `Clone` must copy the whole subtree; a shallow clone would let a mutation
/// leak between two supposedly independent documents.
#[test]
fn clone_is_deep() {
    let original = Value::Compound(Compound::from([(
        BString::from("l"),
        Value::List(vec![Value::Compound(Compound::from([(
            BString::from("n"),
            Value::Int(1),
        )]))]),
    )]));
    let mut copy = original.clone();
    assert_eq!(copy, original);

    let Value::Compound(map) = &mut copy else {
        unreachable!()
    };
    map.insert(BString::from("added"), Value::Byte(1));
    assert_ne!(copy, original);
    assert_eq!(original.as_compound().unwrap().len(), 1);
}

/// `Compound` is a public type alias, and callers build maps with it directly.
/// Whichever backing is compiled in, the map API used across this crate's tests
/// must behave the same.
#[test]
fn compound_alias_supports_the_map_operations_the_codecs_rely_on() {
    let mut m = Compound::new();
    assert!(m.is_empty());
    assert!(m.insert(BString::from("a"), Value::Int(1)).is_none());
    assert_eq!(
        m.insert(BString::from("a"), Value::Int(2)),
        Some(Value::Int(1))
    );
    assert_eq!(m.len(), 1);
    assert!(m.contains_key(&BString::from("a")));
    assert_eq!(m.get(&BString::from("a")), Some(&Value::Int(2)));
    assert_eq!(m.get(&BString::from("missing")), None);

    // `entry().or_insert()` is what implements the first-wins duplicate-key rule
    // in both codecs, so it must keep the existing value on both backings.
    m.entry(BString::from("a")).or_insert(Value::Int(99));
    assert_eq!(m.get(&BString::from("a")), Some(&Value::Int(2)));

    // Keys are raw bytes, so a non-UTF-8 key is a perfectly ordinary key.
    let raw = BString::from(vec![0xffu8, 0x00, 0xfe]);
    m.insert(raw.clone(), Value::Byte(1));
    assert_eq!(m.get(&raw), Some(&Value::Byte(1)));
}

/// Under the default `preserve_order` feature a `Compound` keeps insertion
/// order, which is what makes byte-identical fixture round-trips possible.
#[cfg(feature = "preserve_order")]
#[test]
fn compound_preserves_insertion_order() {
    let mut m = Compound::new();
    for k in ["z", "a", "m"] {
        m.insert(BString::from(k), Value::Int(0));
    }
    let keys: Vec<String> = m.keys().map(ToString::to_string).collect();
    assert_eq!(
        keys,
        ["z", "a", "m"],
        "insertion order must not be sorted away"
    );
}

/// Without `preserve_order` the backing is a sorted `BTreeMap`, so key order is
/// normalised instead. Stated explicitly so the trade-off is visible in both
/// build configurations rather than only in the feature-gated test above.
#[cfg(not(feature = "preserve_order"))]
#[test]
fn compound_sorts_keys_without_preserve_order() {
    let mut m = Compound::new();
    for k in ["z", "a", "m"] {
        m.insert(BString::from(k), Value::Int(0));
    }
    let keys: Vec<String> = m.keys().map(ToString::to_string).collect();
    assert_eq!(keys, ["a", "m", "z"]);
}

/// `Debug` is what every failing assertion in this crate prints, so it must
/// render each variant distinguishably rather than eliding the payload.
#[test]
fn debug_output_names_the_variant_and_its_payload() {
    assert_eq!(format!("{:?}", Value::Byte(1)), "Byte(1)");
    assert_eq!(
        format!("{:?}", Value::IntArray(vec![1, 2])),
        "IntArray([1, 2])"
    );
    assert!(format!("{:?}", Value::String(BString::from("hi"))).contains("hi"));
    // A non-UTF-8 payload must still be printable, not panic.
    let raw = format!("{:?}", Value::String(BString::from(vec![0xffu8])));
    assert!(raw.starts_with("String("));
}
