//! The public surface of [`nbtx::ValueList`], the typed payload of an NBT list.
//!
//! `ValueList` exists to make two wire-format facts un-representable in Rust: a
//! list cannot mix tags, and an *empty* list still names the element type it
//! would have held. These tests pin both, plus the accessor matrix (generated by
//! the same macro `Value` uses, so a mistake in it would be systematic) and the
//! total float equality the type shares with `Value`.
//!
//! No codec is involved, so this file builds without the `nbt`/`snbt` features.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

use bstr::BString;
use nbtx::{Compound, Error, FieldType, Value, ValueList};

fn compound(key: &str, value: Value) -> Compound {
    Compound::from_iter([(BString::from(key), value)])
}

/// One of every payload variant, in tag order, each holding a single element.
fn all_variants() -> Vec<ValueList> {
    vec![
        ValueList::Byte(vec![1]),
        ValueList::Short(vec![2]),
        ValueList::Int(vec![3]),
        ValueList::Long(vec![4]),
        ValueList::Float(vec![5.0]),
        ValueList::Double(vec![6.0]),
        ValueList::ByteArray(vec![vec![7]]),
        ValueList::String(vec![BString::from("8")]),
        ValueList::List(vec![ValueList::Byte(vec![9])]),
        ValueList::Compound(vec![compound("k", Value::Byte(10))]),
        ValueList::IntArray(vec![vec![11]]),
        ValueList::LongArray(vec![vec![12]]),
    ]
}

fn hash_of<T: Hash>(v: &T) -> u64 {
    let mut h = DefaultHasher::new();
    v.hash(&mut h);
    h.finish()
}

// --- element type ---------------------------------------------------------

/// Every variant reports the tag byte the binary encoding writes for it, and
/// `End` reports `TAG_End` — the element type of the list that names none.
#[test]
fn element_type_matches_the_wire_tag() {
    assert_eq!(ValueList::End.element_type(), FieldType::End);
    let expected = [
        FieldType::Byte,
        FieldType::Short,
        FieldType::Int,
        FieldType::Long,
        FieldType::Float,
        FieldType::Double,
        FieldType::ByteArray,
        FieldType::String,
        FieldType::List,
        FieldType::Compound,
        FieldType::IntArray,
        FieldType::LongArray,
    ];
    for (list, tag) in all_variants().iter().zip(expected) {
        assert_eq!(list.element_type(), tag, "{list:?}");
    }
}

/// An empty *typed* list keeps its element type: that is the whole point of the
/// type, and what lets an empty `List<Byte>` re-encode as one.
#[test]
fn an_empty_typed_list_keeps_its_element_type() {
    let empty = ValueList::Byte(Vec::new());
    assert_eq!(empty.element_type(), FieldType::Byte);
    assert!(empty.is_empty());
    assert_eq!(empty.len(), 0);
}

#[test]
fn len_and_is_empty_count_elements() {
    assert_eq!(ValueList::End.len(), 0);
    assert!(ValueList::End.is_empty());
    assert!(ValueList::End.is_end());

    let list = ValueList::Int(vec![1, 2, 3]);
    assert_eq!(list.len(), 3);
    assert!(!list.is_empty());
    assert!(!list.is_end());
}

// --- construction from a `Vec<Value>` -------------------------------------

/// The ergonomic constructor: a homogeneous `Vec<Value>` becomes the typed list
/// its elements describe.
#[test]
fn try_from_types_a_homogeneous_vec() {
    let list = ValueList::try_from(vec![Value::Byte(1), Value::Byte(2)]).expect("homogeneous");
    assert_eq!(list, ValueList::Byte(vec![1, 2]));
    assert_eq!(list.element_type(), FieldType::Byte);
}

/// An empty `Vec` has no element type to recover, so it becomes `End`.
#[test]
fn try_from_an_empty_vec_is_the_end_list() {
    let list = ValueList::try_from(Vec::<Value>::new()).expect("empty is fine");
    assert_eq!(list, ValueList::End);
    assert_eq!(list.element_type(), FieldType::End);
}

/// A mixture has no NBT encoding at all, so it is refused here rather than at
/// write time — and the error names the tag the list settled on plus the first
/// one that differed.
#[test]
fn try_from_a_mixed_vec_is_heterogeneous() {
    let err = ValueList::try_from(vec![
        Value::Byte(1),
        Value::Byte(2),
        Value::String(BString::from("x")),
        Value::Int(9),
    ])
    .expect_err("a mixture cannot be a list");
    match err {
        Error::HeterogeneousList { expected, found } => {
            assert_eq!(expected, FieldType::Byte, "the first element's tag");
            assert_eq!(found, FieldType::String, "the *first* tag that differed");
        }
        other => panic!("expected HeterogeneousList, got {other:?}"),
    }
}

/// Nested lists are typed on the way in too, and the inner element types are
/// free to differ from one another: only the outer `List` tag is shared.
#[test]
fn try_from_types_nested_lists_independently() {
    let list = ValueList::try_from(vec![
        Value::from(ValueList::Byte(vec![1])),
        Value::from(ValueList::String(vec![BString::from("x")])),
        Value::from(ValueList::End),
    ])
    .expect("all three are lists");
    assert_eq!(
        list,
        ValueList::List(vec![
            ValueList::Byte(vec![1]),
            ValueList::String(vec![BString::from("x")]),
            ValueList::End,
        ])
    );
}

// --- push ------------------------------------------------------------------

/// An `End` list has no element type yet, so the first push gives it one (as
/// pmmp/NBT's `ListTag::push` does).
#[test]
fn push_onto_end_adopts_the_element_type() {
    let mut list = ValueList::End;
    list.push(Value::Short(7)).expect("adopts Short");
    assert_eq!(list.element_type(), FieldType::Short);
    list.push(Value::Short(8)).expect("same type");
    assert_eq!(list, ValueList::Short(vec![7, 8]));
}

/// Once adopted, the element type is fixed and a foreign tag is rejected — and
/// the list is left exactly as it was.
#[test]
fn push_of_a_foreign_tag_is_rejected() {
    let mut list = ValueList::Byte(vec![1]);
    let err = list
        .push(Value::Int(2))
        .expect_err("an Int is not a Byte element");
    match err {
        Error::HeterogeneousList { expected, found } => {
            assert_eq!(expected, FieldType::Byte);
            assert_eq!(found, FieldType::Int);
        }
        other => panic!("expected HeterogeneousList, got {other:?}"),
    }
    assert_eq!(list, ValueList::Byte(vec![1]), "the push left no trace");
}

/// `Default` is the untyped empty list, so a default-built list can still adopt
/// any element type.
#[test]
fn default_is_the_end_list() {
    let mut list = ValueList::default();
    assert_eq!(list, ValueList::End);
    list.push(Value::Double(1.5)).expect("adopts Double");
    assert_eq!(list, ValueList::Double(vec![1.5]));
}

// --- reading elements back -------------------------------------------------

#[test]
fn get_boxes_one_element_back_into_a_value() {
    let list = ValueList::Long(vec![10, 20, 30]);
    assert_eq!(list.get(0), Some(Value::Long(10)));
    assert_eq!(list.get(2), Some(Value::Long(30)));
    assert_eq!(list.get(3), None);
    assert_eq!(ValueList::End.get(0), None);
}

/// A nested list comes back out as a `Value::List`, so `get` is total over
/// every variant — including the two that hold containers.
#[test]
fn get_boxes_container_elements_too() {
    let list = ValueList::List(vec![ValueList::Byte(vec![1])]);
    assert_eq!(list.get(0), Some(Value::from(ValueList::Byte(vec![1]))));

    let map = compound("k", Value::Byte(1));
    let list = ValueList::Compound(vec![map.clone()]);
    assert_eq!(list.get(0), Some(Value::Compound(map)));
}

#[test]
fn iter_and_into_iter_agree_with_to_values() {
    let list = ValueList::Int(vec![1, 2, 3]);
    let expected = vec![Value::Int(1), Value::Int(2), Value::Int(3)];

    assert_eq!(list.iter().collect::<Vec<_>>(), expected);
    assert_eq!(list.iter().len(), 3, "the iterator knows its length");
    assert_eq!(list.to_values(), expected);
    assert_eq!(list.clone().into_values(), expected);
    assert_eq!(list.into_iter().collect::<Vec<_>>(), expected);
}

/// The `End` list yields nothing at all, in every iteration form.
#[test]
fn the_end_list_iterates_empty() {
    assert_eq!(ValueList::End.iter().count(), 0);
    assert_eq!(ValueList::End.to_values(), Vec::<Value>::new());
    assert_eq!(ValueList::End.into_values(), Vec::<Value>::new());
}

/// `into_values` is the inverse of `try_from` for every non-empty list.
#[test]
fn into_values_round_trips_through_try_from() {
    for list in all_variants() {
        let values = list.clone().into_values();
        let back = ValueList::try_from(values).expect("still homogeneous");
        assert_eq!(back, list, "{list:?}");
    }
}

// --- accessors -------------------------------------------------------------

/// The `is_*` predicates are macro-generated, so they are checked as a full
/// matrix: exactly one must answer `true` for each variant.
#[test]
fn exactly_one_predicate_matches_each_variant() {
    for (i, list) in all_variants().iter().enumerate() {
        let hits: [bool; 12] = [
            list.is_byte(),
            list.is_short(),
            list.is_int(),
            list.is_long(),
            list.is_float(),
            list.is_double(),
            list.is_byte_array(),
            list.is_string(),
            list.is_list(),
            list.is_compound(),
            list.is_int_array(),
            list.is_long_array(),
        ];
        let matched: Vec<usize> = hits
            .iter()
            .enumerate()
            .filter(|(_, hit)| **hit)
            .map(|(j, _)| j)
            .collect();
        assert_eq!(matched, vec![i], "{list:?}");
        assert!(!list.is_end(), "{list:?}");
    }
}

/// And exactly one `as_*` accessor answers `Some`.
#[test]
fn exactly_one_accessor_matches_each_variant() {
    for (i, list) in all_variants().iter().enumerate() {
        let hits: [bool; 12] = [
            list.as_byte().is_some(),
            list.as_short().is_some(),
            list.as_int().is_some(),
            list.as_long().is_some(),
            list.as_float().is_some(),
            list.as_double().is_some(),
            list.as_byte_array().is_some(),
            list.as_string().is_some(),
            list.as_list().is_some(),
            list.as_compound().is_some(),
            list.as_int_array().is_some(),
            list.as_long_array().is_some(),
        ];
        let matched: Vec<usize> = hits
            .iter()
            .enumerate()
            .filter(|(_, hit)| **hit)
            .map(|(j, _)| j)
            .collect();
        assert_eq!(matched, vec![i], "{list:?}");
    }
}

/// `into_*` hands the payload over on a match and gives the list back untouched
/// otherwise, so a failed conversion loses nothing.
#[test]
fn into_accessors_return_the_payload_or_the_list() {
    assert_eq!(ValueList::Int(vec![1, 2]).into_int(), Ok(vec![1, 2]));
    assert_eq!(
        ValueList::Int(vec![1, 2]).into_byte(),
        Err(ValueList::Int(vec![1, 2]))
    );
    assert_eq!(ValueList::End.into_int(), Err(ValueList::End));
}

// --- conversions -----------------------------------------------------------

/// The `From<Vec<T>>` impls cover the element types with an unambiguous Rust
/// spelling; the three `Vec<Vec<..>>` ones are deliberately absent.
#[test]
fn from_vec_builds_the_matching_variant() {
    assert_eq!(ValueList::from(vec![1_i8]), ValueList::Byte(vec![1]));
    assert_eq!(ValueList::from(vec![1_i16]), ValueList::Short(vec![1]));
    assert_eq!(ValueList::from(vec![1_i32]), ValueList::Int(vec![1]));
    assert_eq!(ValueList::from(vec![1_i64]), ValueList::Long(vec![1]));
    assert_eq!(ValueList::from(vec![1.0_f32]), ValueList::Float(vec![1.0]));
    assert_eq!(ValueList::from(vec![1.0_f64]), ValueList::Double(vec![1.0]));
    assert_eq!(
        ValueList::from(vec![BString::from("a")]),
        ValueList::String(vec![BString::from("a")])
    );
    assert_eq!(
        ValueList::from(vec![compound("k", Value::Byte(1))]),
        ValueList::Compound(vec![compound("k", Value::Byte(1))])
    );
    assert_eq!(
        ValueList::from(vec![ValueList::End]),
        ValueList::List(vec![ValueList::End])
    );
}

#[test]
fn a_list_converts_into_a_value() {
    let value = Value::from(ValueList::Byte(vec![1, 2]));
    assert!(value.is_list(), "a typed list is a `List` tag");
    assert_eq!(value.into_list().expect("a list").len(), 2);
}

// --- equality and hashing --------------------------------------------------

/// `End` and an empty typed list are *different values*: they write a different
/// element-type byte, so conflating them would make the round-trip lossy.
#[test]
fn end_is_not_an_empty_typed_list() {
    assert_ne!(ValueList::End, ValueList::Int(Vec::new()));
    assert_ne!(ValueList::Byte(Vec::new()), ValueList::Int(Vec::new()));
    assert_ne!(
        hash_of(&ValueList::End),
        hash_of(&ValueList::Int(Vec::new())),
        "the element type is hashed, so empty lists do not all collide"
    );
}

/// Lists of different element types never compare equal, whatever they hold.
#[test]
fn different_element_types_are_never_equal() {
    for (i, lhs) in all_variants().iter().enumerate() {
        for (j, rhs) in all_variants().iter().enumerate() {
            assert_eq!(i == j, lhs == rhs, "{lhs:?} vs {rhs:?}");
        }
    }
}

/// The same total float equality `Value` uses: `NaN == NaN` (so `Eq` is
/// reflexive) and `-0.0 == 0.0`, with `Hash` agreeing on both.
#[test]
fn float_equality_is_total() {
    let nan = ValueList::Float(vec![f32::NAN]);
    assert_eq!(nan, nan.clone(), "Eq must be reflexive");
    assert_eq!(hash_of(&nan), hash_of(&ValueList::Float(vec![f32::NAN])));
    assert_eq!(
        nan,
        ValueList::Float(vec![f32::from_bits(0x7fc0_0001)]),
        "every NaN payload is one class"
    );

    let zero = ValueList::Double(vec![0.0]);
    let neg_zero = ValueList::Double(vec![-0.0]);
    assert_eq!(zero, neg_zero);
    assert_eq!(
        hash_of(&zero),
        hash_of(&neg_zero),
        "equal values must hash alike"
    );

    // Ordinary IEEE classes are untouched.
    assert_ne!(ValueList::Float(vec![1.0]), ValueList::Float(vec![2.0]));
    assert_ne!(ValueList::Double(vec![1.0]), nan_double());
}

fn nan_double() -> ValueList {
    ValueList::Double(vec![f64::NAN])
}

/// Length is part of equality, and an element in the wrong place is a different
/// list.
#[test]
fn order_and_length_matter() {
    assert_ne!(ValueList::Int(vec![1, 2]), ValueList::Int(vec![2, 1]));
    assert_ne!(ValueList::Int(vec![1]), ValueList::Int(vec![1, 1]));
}

/// A list is `Eq + Hash`, so it can key a hash map through a `Value`.
#[test]
fn a_list_can_key_a_hash_map() {
    let mut map = std::collections::HashMap::new();
    map.insert(
        ValueList::Compound(vec![compound("k", Value::Float(-0.0))]),
        1,
    );
    assert_eq!(
        map.get(&ValueList::Compound(vec![compound("k", Value::Float(0.0))])),
        Some(&1),
        "`-0.0` and `0.0` are the same key, as they are in `Value`"
    );
}

/// Variable-length element types are written length-first, so the payloads of
/// two elements cannot be read as the payload of one.
///
/// Each pair below is a pair of *unequal* lists whose concatenated payload bytes
/// are identical; without a separator they fed `Hasher::write` the same stream
/// and collided every time. Hash inequality is never a guarantee in general —
/// these assertions are about these specific inputs under `DefaultHasher`, which
/// is what the collision was demonstrated with.
#[test]
fn variable_length_elements_do_not_collide_on_their_boundaries() {
    let pairs: Vec<(ValueList, ValueList)> = vec![
        (
            ValueList::ByteArray(vec![vec![1, 2], vec![]]),
            ValueList::ByteArray(vec![vec![1], vec![2]]),
        ),
        (
            ValueList::String(vec![BString::from("ab")]),
            ValueList::String(vec![BString::from("a"), BString::from("b")]),
        ),
        (
            ValueList::IntArray(vec![vec![1, 2]]),
            ValueList::IntArray(vec![vec![1], vec![2]]),
        ),
        (
            ValueList::LongArray(vec![vec![1, 2]]),
            ValueList::LongArray(vec![vec![1], vec![2]]),
        ),
        (
            ValueList::List(vec![ValueList::Int(vec![1, 2])]),
            ValueList::List(vec![ValueList::Int(vec![1]), ValueList::Int(vec![2])]),
        ),
        (
            ValueList::Compound(vec![compound("ab", Value::Byte(1))]),
            ValueList::Compound(vec![
                compound("a", Value::Byte(1)),
                compound("b", Value::Byte(1)),
            ]),
        ),
    ];

    for (lhs, rhs) in pairs {
        assert_ne!(lhs, rhs, "the two lists are not equal to begin with");
        assert_ne!(
            hash_of(&lhs),
            hash_of(&rhs),
            "{lhs:?} and {rhs:?} must not hash alike"
        );
    }
}

/// The same boundary confusion one level up, in [`Value`]'s own `Hash`.
///
/// Both pairs below hashed identically before the compound entry count and the
/// per-key length were written: the key bytes ran straight into the payload
/// bytes, so where one ended and the other began was not recorded anywhere.
#[test]
fn value_payloads_do_not_collide_on_their_boundaries() {
    let pairs: Vec<(Value, Value)> = vec![
        // "a" + "bc"  vs  "ab" + "c".
        (
            Value::Compound(compound("a", Value::String(BString::from("bc")))),
            Value::Compound(compound("ab", Value::String(BString::from("c")))),
        ),
        // "a" + {"b": 1b}  vs  "ab" + 1b.
        (
            Value::Compound(compound(
                "a",
                Value::Compound(compound("b", Value::Byte(1))),
            )),
            Value::Compound(compound("ab", Value::Byte(1))),
        ),
    ];

    for (lhs, rhs) in pairs {
        assert_ne!(lhs, rhs);
        assert_ne!(
            hash_of(&lhs),
            hash_of(&rhs),
            "{lhs:?} and {rhs:?} must not hash alike"
        );
    }
}

/// The separators must not break the half of the contract that actually has to
/// hold: equal values hash alike, float normalisation included.
#[test]
fn equal_values_still_hash_alike_with_the_separators_in_place() {
    for list in all_variants() {
        assert_eq!(
            hash_of(&list),
            hash_of(&list.clone()),
            "{list:?} must hash to itself"
        );
        assert_eq!(
            hash_of(&Value::List(list.clone())),
            hash_of(&Value::List(list.clone())),
        );
    }

    // ...and across the float normalisation, at every nesting level.
    assert_eq!(
        hash_of(&ValueList::Double(vec![-0.0, f64::NAN])),
        hash_of(&ValueList::Double(vec![
            0.0,
            f64::from_bits(0x7ff8_0000_dead_beef)
        ])),
    );
    assert_eq!(
        hash_of(&ValueList::Compound(vec![compound(
            "k",
            Value::Float(-0.0)
        )])),
        hash_of(&ValueList::Compound(vec![compound("k", Value::Float(0.0))])),
    );
}
